### ISSUE TITLE
[FEAT] Extension 추가하기

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#1]
## 📌  Feature Issue
UI관련 extension을 추가합니다

## 📝  To-do

- [x] TableView Extension 추가하기
- [x] CollectionView Extension 추가하기
- [x] UIView Extension 추가하기
