### ISSUE TITLE
[FEAT] 작성하기뷰 사진 셀 높이 조정 기능 추가, 오토레이아웃 재설정

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#105]
## 📌  Feature Issue

- 작성하기뷰 오토레이아웃 재설정(max, SE)
- 사진 셀 높이 조정 기능 추가

## 📝  To-do

- [x] 작성하기뷰 셀 높이 조정 기능 추가
- [ ] 작성하기뷰 오토레이아웃 점검 - SE 
- [ ] 작성하기뷰 오토레이아웃 점검 - Max
