### ISSUE TITLE
[FEAT] PostDetail View - Title, writer, liked bedge 구현

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#11]
## 📌  Feature Issue

PostDetail View 타이틀, 작성자 정보, 좋아요 뱃지 등의 상단 뷰를 구현합니다.
<img width="480" alt="스크린샷 2021-07-02 오전 12 56 24" src="https://user-images.githubusercontent.com/46644241/124154315-563fb300-dad0-11eb-9a0f-e1e56831ccd9.png">

## 📝  To-do

- [x] 상단 네비게이션 바 embed
- [x] 2줄 타이틀 셋팅
- [x] 작성자 프로필, 이름, 작성일자 구현
- [x] 좋아요 뱃지 구현
