### ISSUE TITLE
[FEAT] 스플래쉬, 온보딩, 로그인 ,텝바 연결하기

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#113]
## 📝  To-do

- [ ] 스플래쉬 구현
- [ ] 스플레쉬 끝난 후 온보딩 연결
- [ ] 온보딩 → 로그인 연결
- [ ] 로그인 후 텝바 연결
