### ISSUE TITLE
[FEAT] HomeView - Today's Drive TVC UI 구현

### ISSUE THREAD

**Issue by comeheredart** [TeamChaRo/ChaRo-iOS#13]
## 📌  Feature Issue

홈뷰에서 오늘의 드라이브 테이블 뷰 셀 UI 를 구성합니다! 
매우 자주 쓰이는 셀이기 때문에 나중에 재활용 할 수 있게 만들겠슴다!

## 📝  To-do

- [x] todo !
- [x] TVC Xib 구성
- [x] TVC 에 CollectionView 생성
- [x] CVC UI 구성 (오토레이아웃)
