### ISSUE TITLE
[BUG] 검색하기 필터뷰 - 필터 선택 버그 처리

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#130]
## 📝 todo
- [ ] 선택안함 관련 로직 다시 짜기
- [ ] 시-도 연결 로직 다시 짜기
- [ ] 필터를 선택 시 검색하기 버튼 활성화 로직 다시 짜기

<details>
<summary> 필요시 참고해주세요🛠</summary>
<div markdown="1">       
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
</div>
</details>
