### ISSUE TITLE
[FEAT] FCM을 위한 프로젝트 세팅 (pushAlarm)

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-iOS#135]
## 📌  Feature Issue
FCM을 위한 프로젝트 세팅

## 📝  To-do
- [ ] firebase에 프로젝트 생성
- [ ] firebase에 앱 등록
- [ ] GoogleService-Info.plist 파일 다운로드하여 프로젝트에 추가
- [ ] firebase SDK 추가
- [ ] 초기화 코드 추가
- [ ] APN 인증 키 추가
