### ISSUE TITLE
[REFACTOR] 작성하기뷰 - 지도 부분 자동완성 알고리즘 고치기   

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#140]
## 📌  Feature Issue

작성하기 지도뷰에서 POI 검색수 줄이고 UI 로직 늦게드는 부분 고치기
## 📝  To-do

- [ ] POI 검색수 줄이기 
- [ ] UI 로직, 비즈니스 로직 뷰모델로 분리하기
- [ ] Rx로 고칠 수 있는지 공부해서 적용하기
