### ISSUE TITLE
[FEAT] 서버데이터 받아오는 시점 조정 ㅋ.ㅋ

### ISSUE THREAD

**Issue by parkikbum** [TeamChaRo/ChaRo-iOS#143]
## 📌  Feature Issue

서버데이터 받아오는 시점 조정 ㅋ.ㅋ

## 📝  To-do

- [ ] todo !
- [ ] 스플래시에서 통신진행을 하는 방안 -> 근데요거 뭔가 힘들거같은데...
- [ ] 스켈레톤 이미지를 이용해서 하는 방안
- [ ] 차로 인디케이터로 해보는 방안

**Comment by parkikbum** [comment]
이름 변경한걸 로티뷰 커밋에 안넣었지만 수정은 완료했습니다.
