### ISSUE TITLE
[REFACTOR] 작성하기 지도뷰 - 최근 검색기록관련 리펙토링하기

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#145]
## 📌  Feature Issue

작성하기 지도뷰 - 최근 검색기록관련 리펙토링합니다.
## 📝  To-do

- [ ] local 에서 저장하는 history 관련로직 생각하기
- [ ] 최근검색기록 없을 때, 있을 때 생각해서 tableview 수정하기
- [ ] tableview header에 최근검색기록, 검색 결과 text 넣기
