### ISSUE TITLE
[FEAT] 마이페이지 리팩토링

### ISSUE THREAD

**Issue by parkikbum** [TeamChaRo/ChaRo-iOS#149]
## 📌  Feature Issue

마이페이지 리팩토링

## 📝  To-do

- [ ] todo !
- [ ] 마이페이지 paging 구현
- [ ] 디자인 수정사항 반영
- [ ] 할수있다면 테이블 뷰 부분 따로 뷰로 구현해서 재사용성?!
