### ISSUE TITLE
[FEAT] 푸시 알림뷰 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-iOS#150]
## 📌  Feature Issue
푸시 알림뷰를 구현합니다.

## 📝  To-do
- [x] 알림뷰 UI 구현
- [x] 알림 클릭 시 뷰 이동 구현
- [x] 알림 상태 분기처리 (읽음, 안읽음)
