### ISSUE TITLE
[FEAT] 게시물 상세보기 - 주차공간, 주의사항 셀 + 공용 title 컴포넌트 만들기 

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#17]
## 📌  Feature Issue

게시물 상세보기에서 주차공간, 주의사항 셀 + 공용 title 컴포넌트 만들려고 합니다. 

## 📝  To-do

- [x] 공용 title 컴포넌트 만들기
- [x] title 사용법 노션에 정리하기
- [x] 주차공간 cell 만들기
- [x] 주의사항 셀 만들기
