### ISSUE TITLE
[FEAT] 홈 애니메이션 뷰 오토 레이아웃 및 네비게이션 바 커스텀

### ISSUE THREAD

**Issue by parkikbum** [TeamChaRo/ChaRo-iOS#18]
## 📌  Feature Issue

홈 애니메이션 뷰 오토 레이아웃 설정
## 📝  To-do

- [x] todo !
- [x] 오토레이아웃 설정
- [x] 네비게이션 바 생성 (UIView)
- [x] 버튼 및 로고 생성
- [x] 그라데이션 효과 설정
- [x] 위치에 따른 이미지 에셋변경
