### ISSUE TITLE
[FEAT] 구경하기 상세보기뷰 - 하단 뷰 디자인 변경

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#182]
## 📌  Feature Issue

<img width="826" alt="image" src="https://user-images.githubusercontent.com/59547116/155123904-35e53917-8903-4406-80d8-4943b00fb7a2.png">

하단 고정 영역으로 변경된 부분 구성합니다. 

## 📝  To-do

- [ ] 하단 레이아웃 잡기
- [ ] 좋아요 기능 연결하기
- [ ] 스크랩 기능 연결하기
