### ISSUE TITLE
[FEAT] ImageLiterals 사용하기

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#184]
## 📌  Feature Issue

ImageLiterals 사용하여 이미지 로드를 합니다. 

## 📝  To-do

- [ ] 사용하지 않는 이미지 삭제하기
- [ ] 사용할 ImageLiterals 이름 맞추기
- [ ] 사용하는 이미지 모두 넣기
