### ISSUE TITLE
[FEAT] 알림뷰 UI 구성하기

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-iOS#186]
## 📌  Feature Issue
알림뷰 UI 구성하기

## 📝  To-do
- [x] 알림뷰 레이아웃 구성하기
- [x] 알림 종류에 맞춰 분기처리하기
- [x] 더미데이터 이용해서 분기처리 확인하기
