### ISSUE TITLE
[FEAT] 상세보기 - 좋아요 리스트 서버 연결

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#189]
## 📌  Feature Issue

구경하기뷰 - 좋아요 리스트 서버 연결합니다. 
## 📝  To-do

- [ ] tableview rxcocoa로 구성하기
- [ ] 구경하기뷰 - 좋아요 리스트 서버 연결하기
- [ ] 로딩 뷰 띄어놓기 or 서버 연결 완료 후 하단 뷰 띄우기
