### ISSUE TITLE
[CHORE] 게시물 상세보기 새로운 서버 데이터 및 디자인으로 수정하기  

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#196]
## 📌  Feature Issue

게시물 상세보기 새로운 서버 데이터 및 디자인으로 수정합니다. 
![image](https://user-images.githubusercontent.com/59547116/158057003-0f820246-258c-4a80-9ea5-25403fbbf436.png)

## 📝  To-do

- [ ] 서버 데이터에 맞게 데이터 전달 수정
- [ ] 위치, 테마 부분 디자인 수정
- [ ] 지도 부분 디자인 수정
