### ISSUE TITLE
[FEAT] HomeView AutoLayout 설정, Cell TitleLabel 생성

### ISSUE THREAD

**Issue by comeheredart** [TeamChaRo/ChaRo-iOS#21]
## 📌  Feature Issue

홈 뷰 TableView 를 디쟌과 협의하면서 완성시킬 예정 !!

## 📝  To-do

- [x] 디쟌과 협의, TableViewCell 높이 계산
- [x] TableView Cell Title Label 생성
- [x] 더보기 버튼 같은 상세 UI 구현
