### ISSUE TITLE
[FEAT] 마이페이지 설정 > 접근허용 기능 구현 & 프로필/비밀번호 수정 뷰 연결

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-iOS#214]
## 📌  Feature Issue
- 마이페이지 설정 > 접근허용, 프로필/비밀번호 수정 기능 구현

## 📝  To-do
- [x] 알림 접근허용 기능 구현
- [x] 사진 접근허용 기능 구현
- [x] 프로필 수정, 비밀번호 수정 뷰 연결
