### ISSUE TITLE
[FEAT] CreatePostVC 코드 정리

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#217]
## 📌  Feature Issue

CreatePostVC 코드를 정리해요
- 접근 제어자 설정
- 가독성 개선
- 코드 그룹핑 개선
- 코드 다시 눈에 익히기

## 📝  To-do

- [ ] 접근 제어자 설정
- [ ] 가독성 개선
- [ ] 코드 그룹핑 개선
- [ ] 코드 다시 눈에 익히기
