### ISSUE TITLE
[FIX] 게시물 상세보기 디자인 QA 받은 부분 수정 

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#219]
## 📌  Feature Issue

게시물 상세보기 디자인 QA 받은 부분 수정합니다. 

## 📝  To-do

- [ ] 좋아요(하트) 눌렀을때 n명이 좋아해요에 카운팅 기능 수정
- [x] 좋아요(하트) 눌르고, 안 눌렀을때 하트 크기 수정
- [x] 스크랩(저장)시 아이콘의 크기 수정
- [ ] 좋아요(하트)가 안 눌러지는 부분 확인
