### ISSUE TITLE
[FEAT] 테마 선택 모달 연결 문제 등 작성하기 개선

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#220]
## 📌  Feature Issue

- 작성하기 화면에 사진 피커 외에 다른 항목 모두 버그나 개선사항 반영

## 📝  To-do

- [ ] 작성하기 화면에 테마 선택 모달을 연결 시 키보드가 보이는 문제 수정
- [ ] 작성하기 화면에 지역선택 피커 예외케이스 처리 보완 (개선)
- [ ] 작성하기 화면에 사진 피커 외에 다른 항목 모두 버그나 개선사항 반영
