### ISSUE TITLE
[FEAT] PostDetail View - image collectionView 구현

### ISSUE THREAD

**Issue by injeong-Choi** [TeamChaRo/ChaRo-iOS#23]
## 📌  Feature Issue

구경하기 뷰의 image collectionView를 구현합니다.
Xib로 구현하여 PostDetailVC에 cell로 연결할 예정입니다.

## 📝  To-do

- [ ] image collectionview 추가
- [ ] autolayout 적용
- [ ] 사진 넘기기 버튼 추가
- [ ] 사진 넘기기 버튼 hidden 분기처리
- [ ] PostDetailVC Cell로 연결
