### ISSUE TITLE
[FEAT] 푸시알림 조회/읽음 기능 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamChaRo/ChaRo-iOS#234]
## 📌  Feature Issue
- 푸시알림 조회/읽음 기능 구현

## 📝  To-do
- [x] 새로 온 푸시를 클릭했을 때 API 연결
- [x] 푸시알림 클릭시 화면 전환
- [x] 푸시알림 클릭시 읽음 처리
