### ISSUE TITLE
[FEAT] 좋아요 리스트에서 다른 사람 계정 누를 경우 → 타인 마이페이지로 이동 

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#237]
## 📌  Feature Issue

좋아요 리스트에서 다른 사람 계정 누를 경우 → 타인 마이페이지로 이동 
## 📝  To-do

- [ ] table view itemSelected 연결
- [ ] 타인 마이페이지로 이동
- [ ] 구경하기 push로 변경
