### ISSUE TITLE
[FEAT] PostDetail View - Image PageControl 구현

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#26]
## 📌  Feature Issue

구경하기 뷰의 image PageControlView를 구현합니다.
Xib로 구현하여 PostDetailVC에 cell로 연결할 예정입니다.
<img width="458" alt="스크린샷 2021-07-06 오전 12 22 00" src="https://user-images.githubusercontent.com/46644241/124493085-3241e180-ddf0-11eb-848b-d6bf210fbebd.png">

## 📝  To-do

- [x] Image PageControlView 추가
- [x] Image Vertical Scroll View 추가
- [x] Autolayout 적용
- [x] 사진 넘기기 버튼 추가
- [x] 사진 넘기기 버튼 hidden 분기처리
- [x] 사진 스크롤로 앞, 뒤 넘기기
- [x] 사진 전환 시 애니메이션 추가
- [x] PostDetailVC Cell로 연결
