### ISSUE TITLE
[BUG] 구경하기에서 좋아요, 스크랩 서버 연결 수정

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#291]
## 🐞 버그 설명

구경하기에서 좋아요, 스크랩 서버 연결 
## 📝 todo
- [ ] 좋아요 서버 연결 수정
- [ ] 좋아요한 사람 수 수정
- [ ] 스크랩 서버 연결 수정 

<details>
<summary> 필요시 참고해주세요🛠</summary>
<div markdown="1">       
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
</div>
</details>
