### ISSUE TITLE
[FEAT] 작성하기 뷰 스토리보드 생성 및 네비게이션, 테이블 뷰 셋팅

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#51]
## 📌  Feature Issue

작성하기 뷰 구현을 위한 초기 셋팅을 합니다.

## 📝  To-do

- [x] 작성하기 스토리 보드, 뷰 컨트롤러 생성
- [x] 테이블 뷰 넣고 Autolayout 적용
- [x] tabbarVC 연결하고 Present 되는 것 확인
