### ISSUE TITLE
[FEAT] 테마 Cell 서버 연동 & 홈 Cell 데이터 전달

### ISSUE THREAD

**Issue by comeheredart** [TeamChaRo/ChaRo-iOS#57]
## 📌  Feature Issue

테마를 눌렀을 때 테마 뷰를 구현합니다.
홈에서 사진 아이콘을 클릭했을 때 다음 셀로 id 를 전달하게 짭니다 ..!

## 📝  To-do

- [x] 데이터 모델 생성
- [x] 테마 눌렀을 때 테마 뷰에서 데이터 뿌려주기
- [ ] 셀 눌렀을 때 postID 와 userID 넘기기
- [x] 서비스 생성
- [x] 서버 연결
