### ISSUE TITLE
[FEAT] Create HomeDataModel & HomeDataService connect to server

### ISSUE THREAD

**Issue by parkikbum** [TeamChaRo/ChaRo-iOS#58]
## 📌  Feature Issue

 Create HomeDataModel & HomeDataService connect to server

## 📝  To-do

- [x] todo !
- [x] constant파일 만들기 (URL정리)
- [x] 홈 데이터 모델 만들기
- [x] 홈 데이터 서비스 만들기 
- [x] 홈화면에 데이터 뿌리기
