### ISSUE TITLE
[FEAT] 작성하기뷰 제목, 사진 cell 구현

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#60]
## 📌  Feature Issue

<img width="708" alt="스크린샷 2021-07-12 오전 5 32 12" src="https://user-images.githubusercontent.com/46644241/125209245-83f7d980-e2d2-11eb-937b-fc585926561f.png">

- 제목 입력 셀 구현
- 사진 입력 셀 구현

## 📝  To-do

- [x] 제목 cell 구현
- [x] 제목 2줄로 넘어가면 셀 크기 조절하는 부분
- [x] 사진 empty cell
- [x] 사진 선택 이후 cell 구현
