### ISSUE TITLE
[FEAT] 더보기 뷰 서버연동

### ISSUE THREAD

**Issue by parkikbum** [TeamChaRo/ChaRo-iOS#64]
## 📌  Feature Issue

더보기 뷰 서버 연동!

## 📝  To-do

- [x] todo !
- [x] 더보기 api 모델/서비스 구현
- [x] 뷰랑 더보기 서버구현
- [x] 홈화면 더보기랑 연동
