### ISSUE TITLE
[FEAT] 작성하기뷰 주차공간, 주의사항, 코스설명 cell 구현

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#71]
## 📌  Feature Issue

작성하기뷰의 주차공간, 주의사항, 코스설명 셀을 구현합니다.

## 📝  To-do

- [x] 주차공간 cell UI Layout 셋팅
- [x] 주의사항 cell UI Layout 셋팅
- [x] 코스설명 cell UI Layout 셋팅
- [ ] 주차공간, 드라이브 버튼 select action 구현
- [ ] 주차공간 설명, 코스설명 textview 글자수 제한 구현
- [ ] x 버튼 작성 중단 alert view 구현
