### ISSUE TITLE
마이 페이지 서버연동

### ISSUE THREAD

**Issue by parkikbum** [TeamChaRo/ChaRo-iOS#79]
## 📌  Feature Issue

마이 페이지 서버연동

## 📝  To-do

- [x] todo !
- [x] 마이페이지 데이터 모델 생성
- [x] 마이페이지 데이터 서비스 생성
- [x] 마이페에지 데이터 연동
