### ISSUE TITLE
[FEAT] 게시물 상세보기 서버연결

### ISSUE THREAD

**Issue by hryeong66** [TeamChaRo/ChaRo-iOS#84]
## 📌  Feature Issue
게시물 상세보기 서버연결합니다.

## 📝  To-do

- [x] 게시물 상세보기 서버에서 데이터 받아오기
- [ ] 작성하기에서 넘겨저온 경우 생각하기
- [x] 지원이랑 얘기해서 postID 넘겨받는 경우 생각하기
- [ ] 수정하기 ActionSheet 생성해서 수정하기

#### 게시물 상세보기 생각해야할 3가지 경로
- [ ] 내 게시물인 경우 → 수정할 수 있는 버튼으로 바꾸기
- [ ] 다른 사람의 게시물인 경우 → 좋아요, 스크랩 버튼
- [ ] 작성하기의 완료 화면으로 볼 경우 

#### 뷰에서 빠진 부분 
- [ ] 네이게이션바 3가지 버전 생각해서 만들기
- [ ] 지도 주소 넣는 셀 index 생각해서 넣기
- [ ] 버튼누르면 클립보드에 복사하는 기능 추가
- [ ] 경로 지정하기
- [ ] map view 안뜨는 부분 확인하기

### 혜령 부분 QA
- [ ] 버튼 간격 다시 짜기
