### ISSUE TITLE
[FEAT] 구경하기뷰 스토리보드 및 테이블뷰 추가

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#9]
## 📌  Feature Issue

구경하기뷰 구현에 앞서, 혜령과 인정의 작업 분담을 위해
스토리보드와 테이블 뷰를 추가합니다.

## 📝  To-do

- [x] 구경하기뷰 스토리보드 추가
- [x] 구경하기뷰 VC 파일 추가
- [x] 구경하기뷰 테이블뷰 추가
- [x] 테이블뷰 VC 파일에 연결
