### ISSUE TITLE
 [FEAT] 작성하기뷰 주차공간, 주의사항, 드라이브코스 Cell 구현

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#90]
## 📌  Feature Issue

<img width="253" alt="스크린샷 2021-07-15 오전 6 08 02" src="https://user-images.githubusercontent.com/46644241/125693147-a8848aa2-2262-42a3-aff8-f78fdf249347.png">
- 주차공간, 주의사항, 드라이브코스 cell 구현

## 📝  To-do

- [x] 주차공간 UI Layout
- [x] 주의사항 UI Layout
- [x] 드라이브코스 UI Layout
- [ ] 주차공간 선택 버튼 기능 구현
- [ ] 주차공간 텍스트필드 기능 구현
- [ ] 드라이브코스 텍스트뷰 기능 구현
