### ISSUE TITLE
[FEAT] 알림 있는척 ㅋㅋ

### ISSUE THREAD

**Issue by parkikbum** [TeamChaRo/ChaRo-iOS#92]
## 📌  Feature Issue

알림 있는척 ㅋㅋ
## 📝  To-do

- [ ] todo !
- [ ] 알림 있는척 ㅋㅋ
- [ ] 알림 있는척 ㅋㅋ
- [ ] 알림 있는척 ㅋㅋ
