### ISSUE TITLE
[BUG] 작성하기뷰 이미지 삭제, 추가 기능 크래시 해결 

### ISSUE THREAD

**Issue by inddoni** [TeamChaRo/ChaRo-iOS#98]
## 🐞 버그 설명

- 사진 추가 시, 누적해서 추가되는 문제
- 사진 삭제 시 index 인식이 잘 되지 않아 index out of range 가 발생하는 문제

## 📝 todo
- [ ] 사진 추가 리스트 append 함수 개선
- [ ] 사진 삭제 index 받아오는 함수 개선
- [ ] 사진 삭제 기능 개선
- [ ] 크래시 개선 확인

<details>
<summary> 필요시 참고해주세요🛠</summary>
<div markdown="1">       
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
</div>
</details>
